[project]
name = "stung"
version = "0.0.1"
description = ""
authors = [
    { name = "HJ Ji", email = "hji20@jh.edu" },
]
license = { text = "MIT" }
readme = ""
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.9",
    "mjol @ git+https://github.com/haydenji0731/mjol.git@main",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "plotly>=6.7.0",
    "pyfastx>=2.3.0",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["stung"]

[tool.setuptools.package-dir]
"" = "src"
